name: Build

on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  wasm-build:
    name: build frontend files
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-wasm
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-wasm-${{ hashFiles('**/Cargo.lock') }}

      - name: install rust toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: wasm32-unknown-unknown

      - name: install cargo-leptos
        run: cargo install --locked cargo-leptos --force

      - name: compile CSS
        uses: ZoeyVid/tailwindcss-update@main
        with:
          input: style/input.css
          output: style/output.css
          params: '--minify'

      - name: cargo leptos build
        run: cargo leptos build --release

      - name: upload frontend files
        uses: actions/upload-artifact@v3
        with:
          name: pkg
          path: target/site/pkg
          if-no-files-found: error

  bin-build:
    name: build server on ${{ matrix.os }}
    needs: [wasm-build]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-cargo
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: install rust toolchain
        if: matrix.os != 'ubuntu-latest'
        uses: dtolnay/rust-toolchain@nightly

      - name: install rust toolchain with aarch64 target
        if: matrix.os == 'ubuntu-latest'
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: x86_64-unknown-linux-musl aarch64-unknown-linux-musl

      - name: install cross and musl
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo install cross --git https://github.com/cross-rs/cross --force
          sudo apt-get -qq -y install musl-tools

      - name: download frontend files
        uses: actions/download-artifact@v3
        with:
          name: pkg
          path: target/site/pkg

      - name: build native
        if: matrix.os != 'ubuntu-latest'
        run: cargo build --package=remote_wol --bin=remote_wol --target-dir=target/server --no-default-features --features=ssr --release

      - name: build linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo build --package=remote_wol --bin=remote_wol --target-dir=target/server --no-default-features --features=ssr --release --target x86_64-unknown-linux-musl
          cross build -v --package=remote_wol --bin=remote_wol --target-dir=target/server-aarch64 --no-default-features --features=ssr --release --target aarch64-unknown-linux-musl

      - name: upload native binary (mac)
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: target/server/release/remote_wol
          if-no-files-found: error

      - name: upload native binary (windows)
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: target/server/release/remote_wol.exe
          if-no-files-found: error

      - name: upload native binary (linux)
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: target/server/x86_64-unknown-linux-musl/release/remote_wol
          if-no-files-found: error

      - name: upload aarch64 binary
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-aarch64
          path: target/server-aarch64/aarch64-unknown-linux-musl/release/remote_wol
          if-no-files-found: error

  make-release:
    name: create release
    needs: [bin-build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: extract version from Cargo.toml
        uses: SebRollen/toml-action@v1.0.2
        id: version
        with:
          file: Cargo.toml
          field: package.version

      - name: download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: create release directory
        run: mkdir release

      - name: create release files
        run: |
          tar -C ./artifacts/ubuntu-latest/remote_wol -czvf ./release/remote_wol-v${{ steps.version.outputs.value }}-linux-x64.tar.gz
          tar -C ./artifacts/ubuntu-latest-aarch64/remote_wol -czvf ./release/remote_wol-v${{ steps.version.outputs.value }}-linux-aarch64.tar.gz
          zip -r ./release/remote_wol-v${{ steps.version.outputs.value }}-windows.zip ./artifacts/windows-latest/remote_wol.exe
          zip -r ./release/remote_wol-v${{ steps.version.outputs.value }}-macos.zip ./artifacts/macos-latest/remote_wol

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          name: remote_wol v${{ steps.version.outputs.value }}
          draft: true
          generate_release_notes: true
          files: |
            release/*.tar.gz
            release/*.zip
