name: Lint

on:
  push:
  pull_request:
  workflow_call:

env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  CARGO_INCREMENTAL: '0'

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: cargo check

  fmt:
    runs-on: ubuntu-latest
    name: Rustfmt
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    name: Clippy
    steps:
      - uses: dtolnay/rust-toolchain@nightly
      - uses: Swatinem/rust-cache@v2
      - uses: actions/checkout@v3
      - run: rustup component add clippy
      - run: cargo clippy -- -Dwarnings
